export type NavigatorList = {
  HomeScreen: any;
  WelcomeScreen: any;
  AboutScreen: any;
  CategoryScreen: any;
  TransactionsScreen: any;
  CameraScreen: any;
  MainContent: any;
  BudgetStack: any;
  Drawer: any;
  ExpensesStack: any;
  IncomeStack: any;
  SavingsStack: any;
  InvestmentStack: any;
  ExpensesScreen: any;
  IncomeScreen: any;
  SavingsScreen: any;
  InvestmentScreen: any;
  MakeParagonsPhotos: any;
  MainContentScreen: any;
  HomeScreenFinal: any;
  ReceiptsStack: any;
};
